### ISSUE TITLE
Enable support for PAE on 32-bit

### ISSUE THREAD

**Issue by bitofhope** [digabi/digabi-os#66]
Booting on an IBM/Lenovo ThinkPad T41 (Intel Pentium M "Banias") fails. The 32-bit linux kernel used in the OS requires the CPU not to support Physical Address Extension. Please change the kernel or add an option for PAE-enabled 32-bit machines to broaden the range of compatible devices.

Error message shown:

```
WARNING: PAE disabled. Use parameter 'forcepae' to enable at your own risk!
This kernel requires the following features not present on the CPU:
pae
Unable to boot - please use a kernel appropriate for your CPU.
```

Bootloader doesn't allow modification of kernel parameters, so can't check with 'forcepae' option.

Steps to reproduce:
1. Try to boot in a machine with a Banias CPU
2. Choose PC 32bit option

**Comment by miasma** [comment]
As far as I can tell, the kernel seems to require PAE, not the opposite. It just can't figure it out since, even though the Banias CPUs support PAE, they don't advertise it. In general, it's a bad idea to force PAE. Also if your laptop has less than 4 GB of RAM, PAE doesn't help at all. It's only useful for machines with 4-64 GB of RAM. If, say 3.3 GB is sufficient for the distro, the 32-bit kernel shouldn't need PAE at all.

**Comment by bitofhope** [comment]
Back when I opened this issue, I was quite confused on the meaning of PAE in this context.

Indeed it seems like the kernel required PAE and didn't recognize the Banias CPU to support it, despite it doing so.

I don't know whether this issue applies to the newest versions. Last time I heard from the devs, this repo was rather behind the actual development version.

As per https://www.ylioppilastutkinto.fi/images/sivuston_tiedostot/Ohjeet/Digabi/ytl_paatelaiteohje_2016_fi.pdf the hardware requirements call for 64 bit CPU anyway so I'll just close this. Feel free to reopen if 32-bit, with or without PAE, turns out relevant. At the time of opening, final hardware requirements had not been published and 32-bit version was apprently still being planned.
