### ISSUE TITLE
Support for Intel AC9000 series network adapters

### ISSUE THREAD

**Issue by xrtli** [digabi/digabi-os#75]
Our school will order a bulk of laptops with either Intel AC8000 or AC9000 series network adapters and on experimenting with Abitti, we noticed that there is no support for 9000 series adapters. Linux kernel has had a driver for 9000 series cards since version 4.14. What is the latest kernel used in Abitti releases? Are there other known compatibility issues when it comes to newer Intel cards?

When to expect a new kernel update?

The card in question is `Intel AC 9560`.
One of the considered devices is `5th Gen Lenovo Thinkpad 11e 29LR`.
https://wireless.wiki.kernel.org/en/users/drivers/iwlwifi

**Comment by xrtli** [comment]
Latest OS version apparently has one kernel option with version 4.14, named Ruthereum. This version does have support for the AC9560 card, according to kernel.org, yet no support for it seems to be available in Abitti.

We wish to see expedited look into this.

**Comment by mplattu** [comment]
Since you have looked into this please provide the name of the relevant driver module. Thanks!

**Comment by xrtli** [comment]
Here is the latest update for the `iwlwifi` driver:
https://git.kernel.org/pub/scm/linux/kernel/git/iwlwifi/iwlwifi-fixes.git/tag/?h=iwlwifi-for-kalle-2017-10-06

**Comment by mplattu** [comment]
It appears that the patches which probably fix your issue will be available on the next LTS kernel or the 4.14 updates. The development for the `iwlwifi` driver is active and ongoing.

The next planned kernel update is taking place on October after the autumn matriculation examination. At the moment we don't have resources to make the update for the mid-May Abitti version since we need to do are several improvements for chemistry and physics exams.

As always, we don't know whether the upgraded 4.14 or a newer LTS kernel fixes your issue. The problem might be in the driver or with the firmware. Thus we don't know whether the WiFi of your fleet will be operational.

Since we will not make any expedited changes (as requested) I will close this issue with `wontfix` flag for now.
